name: Create and publish package

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['release/**']
    

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com
          scope: "@ev-the-dev"

      - run: npm run compile
      - run: cd dist/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
